name: devs_help_devs_backend
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  artemis: '7.0.0-beta.17' # only if you're using ArtemisClient!
  json_annotation: 
  equatable:
  intl: 
  image:
  deep_pick:
  meta: '>=1.0.0 <2.0.0' # only if you have non nullable fields
  gql: 0.13.0
  nhost_sdk:
  nhost_gql_links:

dev_dependencies:
  # lint:
  test: 
  build_runner:
  artemis: '7.0.0-beta.17' # only if you're using ArtemisClient!
  json_serializable: 
